server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    #hostname: peer1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://peer2/eureka/,http://peer3/eureka/
  server:
    enable-self-preservation: false
      #defaultZone: http://peer2/eureka/,http://peer3/eureka/
      #defaultZone: http://peer2:8082/eureka/,http://peer3:8083/eureka/
spring:
  application:
    name: eureka1
#    wait-time-in-ms-when-sync-empty: 0
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
#spring:
#  security:
#    user:
#      name: admin
#      password: pwd
#logging:
#  level:
#    org:
#      springframeword:
#        security: DEBUG